repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.15.7
  hooks:
    - id: ruff
      args: [--fix]
    - id: ruff-format
- repo: local
  hooks:
    - id: mypy
      name: mypy
      entry: poetry run mypy app/
      language: system
      types:
        - python
      pass_filenames: false
- repo: local
  hooks:
    - id: pytest
      name: pytest
      entry: poetry run pytest -m unit --no-header -q
      language: system
      types:
        - python
      pass_filenames: false